import { execFileSync } from 'node:child_process';
import { cp, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

const commit = '1d0ed3b7bc640cdf05b9320e5d514227549bf0c2';
const repository = 'https://github.com/raared/WWUID.git';
const currentResource = 'https://ww1.loping151.top/XutheringWavesUID/resource/map/character';
const root = resolve(import.meta.dirname, '..');
const sourceOption = process.argv.indexOf('--source');
let source = sourceOption >= 0 ? resolve(process.argv[sourceOption + 1] || '') : null;
let temporary;
const statNames = {
  '攻击': 'ATK', '攻击%': 'ATK%', '生命': 'HP', '生命%': 'HP%', '防御': 'DEF', '防御%': 'DEF%',
  '暴击': 'Crit Rate', '暴击伤害': 'Crit DMG', '治疗效果加成': 'Healing Bonus', '共鸣效率': 'Energy Regen',
  '属性伤害加成': 'AttributeDMG', '技能伤害加成': 'SkillDMG',
  '普攻伤害加成': 'Basic Attack DMG Bonus', '重击伤害加成': 'Heavy Attack DMG Bonus',
  '共鸣技能伤害加成': 'Resonance Skill DMG Bonus', '共鸣解放伤害加成': 'Resonance Liberation DMG Bonus'
};

try {
  if (!source) {
    temporary = await mkdtemp(join(tmpdir(), 'wwuid-sync-'));
    execFileSync('git', ['init', '-q', temporary]);
    execFileSync('git', ['-C', temporary, 'fetch', '-q', '--depth', '1', repository, commit], { timeout: 60_000 });
    execFileSync('git', ['-C', temporary, 'checkout', '-q', '--detach', 'FETCH_HEAD']);
    source = temporary;
  }
  await sync(source);
} finally {
  if (temporary) await rm(temporary, { recursive: true, force: true });
}

async function sync(sourceRoot) {
  if (sourceOption < 0) {
    const actualCommit = execFileSync('git', ['-C', sourceRoot, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
    if (actualCommit !== commit) throw new Error(`WWUID 版本不匹配：期望 ${commit}，得到 ${actualCommit}`);
  }

  const mapRoot = join(sourceRoot, 'WutheringWavesUID/utils/map/character');
  const characterNames = parseCharacterNames(await readFile(join(sourceRoot, 'WutheringWavesUID/utils/resource/constant.py'), 'utf8'));
  const idsByName = Object.entries(characterNames).reduce((result, [id, name]) => {
    (result[name] ||= []).push(id);
    return result;
  }, {});
  const ruleSets = {};
  const unmapped = [];
  let templateCount = 0;
  let conditionCount = 0;

  for (const entry of await readdir(mapRoot, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name === 'default') continue;
    const ids = idsByName[entry.name];
    if (!ids) { unmapped.push(entry.name); continue; }
    const directory = join(mapRoot, entry.name);
    const files = (await readdir(directory)).filter(name => name.startsWith('calc') && name.endsWith('.json')).sort();
    const templates = {};
    for (const file of files) templates[file] = convert(JSON.parse(await readFile(join(directory, file), 'utf8')));
    const conditionFile = (await exists(join(directory, 'condition-user.json'))) ? 'condition-user.json' : 'condition.json';
    const conditions = await exists(join(directory, conditionFile))
      ? JSON.parse(await readFile(join(directory, conditionFile), 'utf8')) : [];
    for (const id of ids) ruleSets[id] = {
      characterName: entry.name,
      attribute: attributeFor(id),
      defaultTemplate: 'calc.json',
      templates,
      conditions
    };
    templateCount += files.length;
    conditionCount += conditions.length;
  }

  characterNames['1108'] ||= 'Hiyuki';
  const hiyukiResponse = await fetch(`${currentResource}/1108/calc.json`, { signal: AbortSignal.timeout(15_000) });
  if (hiyukiResponse.ok) {
    characterNames['1108'] = '绯雪';
    ruleSets['1108'] = {
      characterName: '绯雪', attribute: 'Glacio', defaultTemplate: 'calc.json',
      templates: { 'calc.json': convert(await hiyukiResponse.json()) }, conditions: []
    };
    templateCount += 1;
  }
  const meta = {
    repository,
    commit,
    currentResource,
    license: 'GPL-3.0-only',
    characterDirectories: new Set(Object.values(ruleSets).map(rule => rule.characterName)).size,
    characterIds: Object.keys(ruleSets).length,
    templates: templateCount,
    conditions: conditionCount,
    unmapped
  };
  const output = `// Generated by npm run sync:wwuid. Do not edit by hand.\n` +
    `export const wwuidMeta = ${JSON.stringify(meta, null, 2)};\n\n` +
    `export const characterRuleSets = ${JSON.stringify(ruleSets, null, 2)};\n\n` +
    `export const characterNames = ${JSON.stringify(characterNames, null, 2)};\n\n` +
    `export const weaponNames = ${JSON.stringify({ '21020076': '永耀星辉', '21020086': 'Frostburn' }, null, 2)};\n\n` +
    `export const sonataNames = ${JSON.stringify({ 8: '轻云出月', 11: '此间永驻之光' }, null, 2)};\n`;
  await writeFile(join(root, 'character-rules.js'), output);
  await writeFile(join(root, 'wwuid-sync-report.json'), `${JSON.stringify(meta, null, 2)}\n`);
  await cp(join(sourceRoot, 'LICENSE'), join(root, 'LICENSE'));
  console.log(`已同步 ${meta.characterDirectories} 个角色目录、${meta.characterIds} 个角色 ID、${templateCount} 个评分模板。`);
}

function convert(config) {
  const costs = [1, 3, 4];
  return {
    name: config.name,
    mainWeights: Object.fromEntries(costs.map(cost => [cost, mapWeights(config.main_props[cost])])),
    subWeights: mapWeights(config.sub_props),
    skillWeights: Object.fromEntries(['Basic Attack DMG Bonus', 'Heavy Attack DMG Bonus', 'Resonance Skill DMG Bonus', 'Resonance Liberation DMG Bonus']
      .map((name, index) => [name, config.skill_weight[index]])),
    maxScoreByCost: Object.fromEntries(costs.map((cost, index) => [cost, config.score_max[index]])),
    thresholdsByCost: Object.fromEntries(costs.map((cost, index) => [cost, config.props_grade[index]])),
    totalThresholds: config.total_grade
  };
}

function mapWeights(weights) {
  return Object.fromEntries(Object.entries(weights).map(([name, value]) => {
    if (!statNames[name]) throw new Error(`未知 WWUID 词条：${name}`);
    return [statNames[name], value];
  }));
}

function parseCharacterNames(source) {
  const start = source.indexOf('CHAR_DETAIL = {');
  const end = source.indexOf('\n}\n', start);
  if (start < 0 || end < 0) throw new Error('无法读取 WWUID CHAR_DETAIL');
  return Object.fromEntries([...source.slice(start, end).matchAll(/^\s*"(\d+)": \{.*?"name": "([^"]+)"/gm)]
    .map(([, id, name]) => [id, name]));
}

function attributeFor(id) {
  return ({ 1: 'Glacio', 2: 'Fusion', 3: 'Electro', 4: 'Aero', 5: 'Spectro', 6: 'Havoc' })[String(id)[1]];
}

async function exists(path) {
  try { await readFile(path); return true; } catch (error) {
    if (error.code === 'ENOENT') return false;
    throw error;
  }
}
